pattern = \
 {
    'Внутренний id лота': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'SapId'},
    'Наименование лота': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'Name'},
    'Юридическое лицо': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'CustomerOrganization'},
    'Филиал/Подразделение': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'CustomerSubdivision'},
    'Функциональный блок': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'CustomerFunctionalBlock'},
    'Планируемый способ закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'PlannedPurchaseMethodCode'},
    'Организатор закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'CustomerOrganizer'},
    'Вид закупки (электронная/неэлектронная)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'IsElectronicPurchase'},
    'Наличие условий о субъектах малого и среднего предпринимательства в конкурсной/закупочной документации': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ForSmallOrMiddle'},
    'Признак закупки инновационной и высокотехнологичной продукции': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'IsInIpr'},
    'Является ИПР (Да/Нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'IsInnovation'},
    'Является ОНМ (Да/Нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'IsONM'},
    'В рамках БДР (Да/Нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'IsInBdr'},
    'Группа продукции (Код классификатора)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ProductGroupId'},
    'Вид закупаемой продукции': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ProductTypeId'},
    'Код по ОКВЭД2': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'OkvedId'},
    'Код по ОКДП2': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'OkdpId'},
    'Код вида деятельности': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'CodeActivityId'},
    'Источник финансирования': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'PurchaseRequestFinanceSources'},
    'Документ, на основании которого определена планируемая цена закупки*': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'PurchasePriceDocumentCode'},
    'Планируемая (предельная) цена закупки по ПЗ в текущих ценах, тыс. руб. без НДС': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedSumNotax'},
    'Планируемая (предельная) цена закупки по ПЗ в текущих ценах, тыс. руб. с учетом НДС': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedSumTax'},
    'Планируемая (предельная) цена закупки с учетом снижения инвестиционных затрат на 30 % относительно уровня 2012 года, руб без НДС': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedSumWith30PercReductionNotax'},
    'Планируемая цена закупки с учетом снижения инвестиционных затрат на 30 % относительно уровня 2012 года, руб с учетом НДС': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedSumWith30PercReductionTax'},
    'Планируемая начальная (предельная) цена лота по извещению/уведомлению, тыс. руб. без НДС': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedSumByNotificationNotax'},
    'Планируемая начальная (предельная) цена лота по извещению/уведомлению, тыс. руб. c НДС': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedSumByNotificationTax'},
    'Плановая дата официального объявления о начале процедур': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'PublicationPlannedDate'},
    'Категория закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'PurchaseCategory_Id'},
    'Плановая дата подведения итогов по закупочной процедуре': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'SummingupTime'},
    'Год под обеспечение потребности которого планируется данная закупка': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'PlannedPurchaseYear'},
    'Дополнительная информация по закупке': {'excel_type': 1, 'data_type': 'nvarchar(max)', 'asuzd_name': 'AdditionalInfo'},
    'Примечание': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'Note'},
    'Тип потребности': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'AdditionalPRAttributeId'},
    'Минимально необходимые требования, предъявляемые к закупаемым товарам (работам, услугам)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'MinRequirementsForPurchaseGoods'},
    'Количество': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'Qty'},
    'ЕИ Код по ОКЕИ': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'Okeiguid'},
    'Регион поставки товаров / Код по ОКАТО': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'Okato'},
    'Регион поставки товаров / Наименование ОКАТО': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'DeliveryPlace'},
    'Плановая дата заключения договора': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'PlannedDateOfContract'},
    'Плановая дата начала поставки товаров, выполнения работ, услуг': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'PlannedDateOfDelivery'},
    'Плановая дата окончания поставки товаров, выполнения работ, услуг': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'PlannedDateOfCompletion'},
    '(заполняется только в случае заукпки у ЕП) Основание для проведения закупки у ЕИ (Положение, дата утверждения, пункт положения)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ReasonPurchaseEP'},
    '(заполняется только в случае заукпки у ЕП) Наименование контрагента': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ContractorName'},
    '(заполняется только в случае закупки у ЕП) ИНН контрагента': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ContractorInn'},
    '(заполняется только в случае закупки у ЕП) КПП': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ContractorKpp'},
    'ИПР год': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'IprYear'},
    'Код объекта в инвестиционной программе': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'InvestProjectCode'},
    'Наименование инвестиционного проекта': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'InvestProjectName'},
    'Дата утверждения проектно-сметной документации': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ConstructionDocumentsState'},
    'Ввод объекта в эксплуатацию/ окончание работ по проекту (месяц, год)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'DateEndProject'},
    'Сметная стоимость объекта в тек. ценах, руб. с НДС': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'CostProject'},
    'Физические параметры инвестиционного проекта МВт': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'MegaWatt'},
    'Физические параметры инвестиционного проекта MBA': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'Mba'},
    'Физические параметры инвестиционного проекта км': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'Kilometer'},
    'Технологическое присоединение (Да/Нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'ProcessConnection'},
    'Льготное технологическое присоединение (Да/Нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'PrivilegedProcessConnection'},
    'Номер закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': ''}
 }
