pattern = \
 {
   'внутренний id лота': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'sapid'},
   'наименование лота': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'name'},
   'юридическое лицо': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'customerorganization'},
   'филиал/подразделение': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'customersubdivision'},
   'функциональный блок': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'customerfunctionalblock'},
   'планируемый способ закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'plannedpurchasemethodcode'},
   'организатор закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'customerorganizer'},
   'вид закупки (электронная/неэлектронная)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'iselectronicpurchase'},
   'наличие условий о субъектах малого и среднего предпринимательства в конкурсной/закупочной документации': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'forsmallormiddle'},
   'признак закупки инновационной и высокотехнологичной продукции': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'isinnovation'},
   'является ипр (да/нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'isinipr'},
   'является онм (да/нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'isonm'},
   'в рамках бдр (да/нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'isinbdr'},
   'группа продукции (код классификатора)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'productgroupid'},
   'вид закупаемой продукции': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'producttypeid'},
   'код по оквэд2': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'okvedid'},
   'код по окдп2': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'okdpid'},
   'код вида деятельности': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'codeactivityid'},
   'источник финансирования': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'purchaserequestfinancesources'},
   'документ, на основании которого определена планируемая цена закупки*': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'purchasepricedocumentcode'},
   'планируемая (предельная) цена закупки по пз в текущих ценах, тыс. руб. без ндс': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedsumnotax'},
   'планируемая (предельная) цена закупки по пз в текущих ценах, тыс. руб. с учетом ндс': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedsumtax'},
   'планируемая (предельная) цена закупки с учетом снижения инвестиционных затрат на 30 % относительно уровня 2012 года, руб без ндс': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedsumwith30percreductionnotax'},
   'планируемая цена закупки с учетом снижения инвестиционных затрат на 30 % относительно уровня 2012 года, руб с учетом ндс': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedsumwith30percreductiontax'},
   'планируемая начальная (предельная) цена лота по извещению/уведомлению, тыс. руб. без ндс': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedsumbynotificationnotax'},
   'планируемая начальная (предельная) цена лота по извещению/уведомлению, тыс. руб. c ндс': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedsumbynotificationtax'},
   'плановая дата официального объявления о начале процедур': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'publicationplanneddate'},
   'категория закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'purchasecategory_id'},
   'плановая дата подведения итогов по закупочной процедуре': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'summinguptime'},
   'год под обеспечение потребности которого планируется данная закупка': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'plannedpurchaseyear'},
   'дополнительная информация по закупке': {'excel_type': 1, 'data_type': 'nvarchar(max)', 'asuzd_name': 'additionalinfo'},
   'примечание': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'note'},
   'тип потребности': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'additionalprattributeid'},
   'минимально необходимые требования, предъявляемые к закупаемым товарам (работам, услугам)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'minrequirementsforpurchasegoods'},
   'количество': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'qty'},
   'еи код по океи': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'okeiguid'},
   'регион поставки товаров / код по окато': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'okato'},
   'регион поставки товаров / наименование окато': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'deliveryplace'},
   'плановая дата заключения договора': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'planneddateofcontract'},
   'плановая дата начала поставки товаров, выполнения работ, услуг': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'planneddateofdelivery'},
   'плановая дата окончания поставки товаров, выполнения работ, услуг': {'excel_type': 3, 'data_type': 'datetime', 'asuzd_name': 'planneddateofcompletion'},
   '(заполняется только в случае заукпки у еп) основание для проведения закупки у еи (положение, дата утверждения, пункт положения)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'reasonpurchaseep'},
   '(заполняется только в случае заукпки у еп) наименование контрагента': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'contractorname'},
   '(заполняется только в случае закупки у еп) инн контрагента': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'contractorinn'},
   '(заполняется только в случае закупки у еп) кпп': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'contractorkpp'},
   'ипр год': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'ipryear'},
   'код объекта в инвестиционной программе': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'investprojectcode'},
   'наименование инвестиционного проекта': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'investprojectname'},
   'дата утверждения проектно-сметной документации': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'constructiondocumentsstate'},
   'ввод объекта в эксплуатацию/ окончание работ по проекту (месяц, год)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'dateendproject'},
   'сметная стоимость объекта в тек. ценах, руб. с ндс': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'costproject'},
   'физические параметры инвестиционного проекта мвт': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'megawatt'},
   'физические параметры инвестиционного проекта mba': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'mba'},
   'физические параметры инвестиционного проекта км': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'kilometer'},
   'технологическое присоединение (да/нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'processconnection'},
   'льготное технологическое присоединение (да/нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'privilegedprocessconnection'},
   'номер закупки': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'lotnumber'},
   'долгосрочная потребность (да/нет)': {'excel_type': 1, 'data_type': 'nvarchar(255)', 'asuzd_name': 'islongtermpurchase'},
   'год оплаты': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'paymentyear'},
   'сумма оплаты (с учетом ндс)': {'excel_type': 2, 'data_type': 'float', 'asuzd_name': 'paymentsummwithtax'}
 }
